### ISSUE TITLE
[SURE-5880] Can not deploy 1.23 eks clusters

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#103]
#### Issue description:
Can not provision or upgrade to 1.23+ with EKS clusters though they are listed as supported

#### Business impact:
Scheduled upgrades of many environments (including prod) is blocked

#### Troubleshooting steps:
Reproduced
Checked the eks kontainer-engine in 2.6.10: https://sourcegraph.com/github.com/rancher/rancher@v2.6.10/-/blob/pkg/kontainer-engine/drivers/eks/eks_driver.go?L46&subtree=true

#### Repro steps:

Attempt to deploy 1.23 EKS cluster using Rancher 2.6.10 and region us-east-1 (though I believe the behavior is the same for other regions

#### Alternatively

 Deploy 1.22 EKS cluster
Attempt to upgrade to 1.23

#### Workaround:
Is workararound available and implemented? no

We believe if we capture the API request for a 1.22 upgrade and replace the k8s version we should be able to push a 1.23 upgrade, but we need to test before proposing to Pfizer

#### Actual behavior:
Can not deploy or upgrade to 1.23

#### Expected behavior:
As 1.23 is listed as supported in the [support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-10/), in the [driver's manifest](https://sourcegraph.com/github.com/rancher/rancher@v2.6.10/-/blob/pkg/kontainer-engine/drivers/eks/eks_driver.go?L46&subtree=true), and available for the region in EKS, we expect to be able to deploy and upgrade to it in Rancher UI

**Comment by richardcase** [comment]
I have tested upgrading a EKS 1.22 cluster (created via the UI) using API request to v1.23.

The steps i took are
* Created an API key in Rancher Manager and took note of the the bearer token and API endpoint
  * The bearer token is needed when making requests below for the `Authorization` header. The header value will be **Bearer <insertyourbearertoken>** 
* Get the cluster details using this request (using Postman)
  * GET https://b0bb-5-71-200-124.eu.ngrok.io/v3/clusters/c-qzxcc
  * Where `https://b0bb-5-71-200-124.eu.ngrok.io/v3` is the API endpoint and `c-qzxcc` is the cluster identifier (this can be found when you navigate to your cluster in Rancher Manager from the URL)
* Upgraded the control plane to 1.23 first by sending this API request (using Postman)
  * PUT https://b0bb-5-71-200-124.eu.ngrok.io/v3/clusters/c-qzxcc
```json
{
    "name": "richtest122",
    "eksConfig": {
        "kubernetesVersion": "1.23",
        "nodeGroups": [
            {
                "desiredSize": 1,
                "diskSize": 20,
                "ec2SshKey": "richard-capi",
                "gpu": false,
                "imageId": null,
                "instanceType": "t3.medium",
                "labels": {},
                "launchTemplate": null,
                "maxSize": 1,
                "minSize": 1,
                "nodegroupName": "ng1",
                "requestSpotInstances": false,
                "resourceTags": {},
                "spotInstanceTypes": null,
                "subnets": [
                    "subnet-0e1a14ea0de97cf6e",
                    "subnet-08a9caad3d1ef363d",
                    "subnet-02f7d904ddc5ee271"
                ],
                "tags": {},
                "type": "/v3/schemas/nodeGroup",
                "userData": null,
                "version": "1.22"
            }
        ]
    }
}
```
  * The important part is setting `kubernetesVersion` to **1.23**
  * you need to copy the nodegroup information from the response of the GET (above)
  * The `state` will change to **updating**
  * Wait until the `state` changes back to **active** (you can use the GET request above to get the latest state)
* Upgraded the node group to v1.23 by sending the following request:
  * PUT https://b0bb-5-71-200-124.eu.ngrok.io/v3/clusters/c-qzxcc
```json
{
    "name": "richtest122",
    "eksConfig": {
        "nodeGroups": [
            {
                "desiredSize": 1,
                "diskSize": 20,
                "ec2SshKey": "richard-capi",
                "gpu": false,
                "imageId": null,
                "instanceType": "t3.medium",
                "labels": {},
                "launchTemplate": null,
                "maxSize": 1,
                "minSize": 1,
                "nodegroupName": "ng1",
                "requestSpotInstances": false,
                "resourceTags": {},
                "spotInstanceTypes": null,
                "subnets": [
                    "subnet-0e1a14ea0de97cf6e",
                    "subnet-08a9caad3d1ef363d",
                    "subnet-02f7d904ddc5ee271"
                ],
                "tags": {},
                "type": "/v3/schemas/nodeGroup",
                "userData": null,
                "version": "1.23"
            }
        ]
    }
}
``` 
  * The `state` will change to **updating** and then back to **active** once the upgrade has completed.

**Comment by richardcase** [comment]
I'm going to test it again and see if it's possible to not include the `nodeGroups` in the first request.

**Comment by richardcase** [comment]
The first request to upgrade the control plane (i.e. the EKS service) can be simplified so the body doesn't include the nodegroup information:

```json
{
    "name": "richtest122",
    "eksConfig": {
        "kubernetesVersion": "1.23"
    }
}
```

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6.10
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: eks

----------

### Testing: ###
Tested the following, grabbed from internal discussion:
1. provisioning a fresh install EKS cluster of 1.23
2. Upgrading from 1.22 to 1.23 and ensuring it works fine. Edit cluster, and verify if you are able to upgrade nodegroups after.
3. Upgrade to 2.7-head or 2.7.1, and ensure the cluster is Active. Edit cluster and add a nodegroup to check if that continues to work
4. It will be interesting to see how Rancher UI behaves when CP (Cluster itself) is on 1.23 while UI doesn’t technically allow 1.23, e.g.:
- Will be users be able to open “Edit Cluster” without errors
- Will they be able to add additional node groups or change any other cluster settings and successfully save them with cluster remaining on 1.23?
- When adding new node groups, will they be limited to 1.22 since 1.23 is not available?
- Will they be able to upgrade existing nodegroups to 1.23 (not sure if it’s necessary for their case given

**Results**
1. provisioning a fresh install EKS cluster of 1.23 - **N/A**
-  Provisioning a 1.23 eks cluster on 2.6.10 is not possible through the UI and the internal script was just for upgrading existing eks clusters.
2. Upgrading from 1.22 to 1.23 and ensuring it works fine. Edit cluster, and verify if you are able to upgrade nodegroups after. - **Pass**
3. Upgrade to 2.7-head or 2.7.1, and ensure the cluster is Active. Edit cluster and add a nodegroup to check if that continues to work - **Pass**
4. It will be interesting to see how Rancher UI behaves when CP (Cluster itself) is on 1.23 while UI doesn’t technically allow 1.23, e.g.:
- Will be users be able to open “Edit Cluster” without errors
  - User is able to edit cluster config after upgrading to 1.23 using the api ![image](https://user-images.githubusercontent.com/108360907/218861812-bb82c338-f46d-4506-9cff-23dce23b4213.png)
- Will they be able to add additional node groups or change any other cluster settings and successfully save them with cluster remaining on 1.23?
  - Yes
- When adding new node groups, will they be limited to 1.22 since 1.23 is not available?
  - New node groups were created as 1.23 versions
  - ![image](https://user-images.githubusercontent.com/108360907/218881896-9ce5d19b-c13f-4380-a975-b285147091e9.png)

- Will they be able to upgrade existing nodegroups to 1.23 (not sure if it’s necessary for their case given)
  - After upgrading user is given the option to upgrade existing nodegroups

**Comment by kkaempf** [comment]
See https://github.com/rancherlabs/support-tools/pull/216
