### ISSUE TITLE
[Feature] K8s 1.27 support 

### ISSUE THREAD

**Issue by vardhaman22** [rancher/eks-operator#241]
issue: https://github.com/rancher/rancher/issues/41840

- k8s deps bump to 0.27.x required.
- need to use latest 1.5.0 rc tag available for rke
- other dependencies
```
github.com/rancher/wrangler v1.1.1-0.20230831050635-df1bd5aae9df
github.com/rancher/lasso v0.0.0-20230830164424-d684fdeb6f29
github.com/rancher/fleet/pkg/apis v0.0.0-20230901075223-437edb7091f5

```
- after that new changes needs to be vendored in rancher

PR's:
- [ ] https://github.com/rancher/eks-operator/pull/248
- [ ] https://github.com/rancher/eks-operator/pull/249

**Comment by mjura** [comment]
@vardhaman22, @mitulshah-suse hi, can you please tell us how did you generated version for these modules, because https://github.com/rancher/rancher/blob/release/v2.8/go.mod is still using older versions of them.

Bumping versions for all these modules will also impact Rancher v2.8, because Rancher is including AKS/GKE/EKS operators as go modules.

**Comment by cpinjani** [comment]
Can we merge PRs since https://github.com/rancher/rancher/pull/42808 is merged ?

**Comment by vardhaman22** [comment]
Hi @cpinjani, yes PRs can be merged....just one thing though .. i see rancher/pkg/apis is a dependency is a dependency in go.mod can we update that to latest as well ?

**Comment by kkaempf** [comment]
considered done
