### ISSUE TITLE
(SURE-5259) EKS Provision Failure w/ Rancher2 Terraform Provider

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#85]
Seems very similar to SURE-4066

#### Issue description:
Can't provision an EKS downstream cluster using the Rancher2 TF provider. This is the error we see in the Rancher UI on the cluster as well as inside the eks-config-operator pod logs (it is spammed continuously):
```
time="2022-09-13T23:43:46Z" level=error msg="error syncing 'cattle-global-data/c-ksl6p': handler eks-controller: InvalidParameterException: Launch template details can't be null for Custom ami type node group\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"eca6e2f1-42d5-411f-b2fc-716404d09d13\"\n  },\n  Message_: \"Launch template details can't be null for Custom ami type node group\"\n}, requeuing" 
```
Cloud Trail on the AWS backned is reporting this error for the EventType: UpdateNodegroupVersion

#### Error code
InvalidParameterException

Event Record.
```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "AIDA4SBL6SADYCHEP64QO",
        "arn": "arn:aws:iam::863380606983:user/srvamr-btcsapid",
        "accountId": "1111111111111",
        "accessKeyId": "XXXXXXXXXXXXXXXXXXXXXXXX",
        "userName": "srvamr-btcsapid"
    },
    "eventTime": "2022-09-02T19:42:50Z",
    "eventSource": "eks.amazonaws.com",
    "eventName": "UpdateNodegroupVersion",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "148.168.40.5",
    "userAgent": "aws-sdk-go/1.36.7 (go1.16.4; linux; amd64)",
    "errorCode": "InvalidParameterException",
    "requestParameters": {
        "nodegroupName": "pdcs-dev1d-harim-v2-090122-ng1",
        "clientRequestToken": "D9CB6CAB-3459-4E09-89F0-DE4CF3BB6CAE",
        "name": "pdcs-dev1d-harim-v2-090122",
        "version": "1.21"
    },
    "responseElements": {
        "message": "Launch template details can't be null for Custom ami type node group"
    },
    "requestID": "9b15e35e-8349-4f9f-9586-62e94e253308",
    "eventID": "6bbdb28c-3b56-4011-90a6-27f791fdf035",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "863380606983",
    "eventCategory": "Management"
}
```
the payload for UpdateNodegroupVersion is expecting LaunchTemplate details which the payload is missing 

see: https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupVersion.html

The user is using a Launch Template with a custom AMI. It appears that the problem might be because the payload is adding "version": "1.21" as you can see above. The AWS [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.update_nodegroup_version) says: " If you specify launchTemplate , and your launch template uses a custom AMI, then don't specify releaseVersion , or the node group update will fail."

So we are wondering if this is the problem here. If so, why is the version being supplied in the payload when it shouldn't be? The user said that when he manually uses the following payload/method with the AWS SDK then it works fine:
```
response = eks.update_nodegroup_version(
  clusterName = cluster_name,
  nodegroupName = nodeGroup,
  launchTemplate = {
    'name': launchTemplateName,
  },
  force=True
)
```
The user said this was working fine 3 weeks ago. Did something change with the AWS SDK or how we handle it?  We did notice this but not sure if it is related:
https://github.com/rancher/eks-operator/pull/72

When we looked at the user's AWS console, the EKS cluster was healthy, the Node Groups were created and healthy as well.

#### Business impact:
This is a blocker for them as they are not able to get their automation to work

#### Troubleshooting steps:
I tried to reproduce the problem in-house. I can get a vanilla EKS cluster to work fine. I am currently trying to test it with Launch Templates and a custom AMI like the user, but I am running into some other issues (AWS permissions which I'm working to get resolved). Once  my permissions in AWS get fixed, I'm hoping I can reproduce the problem.

#### Workaround:
Is workararound available and implemented? yes/no
What is the workaround:

#### Actual behavior:
EKS cluster with Launch Template and custom AMI should be provisioned successfully

#### Expected behavior:
EKS cluster with Launch Template and custom AMI is not provisioned successfully

**Comment by salasberryfin** [comment]
After further investigation, this is not strictly related to Terraform but to any cluster managed by the eks-operator. The issue comes from the way version updates work in EKS node groups:
- "Standard" node groups, which are those created without a custom launch template, can be updated to a newer version by simply using the AWS SDK `UpdateNodegroupVersion` with the specific version the node group is expected to update to.
- Node groups created from a custom launch template (which use a custom AMI) cannot just be updated to a newer version. The only way to update these node groups is to create a new version of the launch template and point this node group to the newer version. Underneath, the AMI used by the launch template can be updated as well for new versions of the template.

The eks-operator does not manage these different behaviors, depending on how node groups are originally created, and hence submit a malformed request to `UpdateNodegroupVersion` in the specific case of a custom launch template node group, causing the reported error.

Version updates for node groups should follow:
- Node groups without a custom launch template can be updated by just specifying the new version, which aligns with the option shown in the Rancher UI.
- Node groups created from a custom launch template cannot be updated to a new version (ideally we should remove this option from Rancher dashboard). The correct way to update these node groups is to update the launch template version (which is possible from Rancher UI).

I'm currently validating a solution to this and will be creating a PR soon.

**Comment by salasberryfin** [comment]
Created PR #186 with a proposal to fix this issue.

**Comment by cpinjani** [comment]
Validated the issue on build: `v2.7-5f98b0f28bc8a48366e9ced8f0a0fea3d826d90d-head`, updating Node group with new version of custom Launch template is giving error.

Steps:
- Provision EKS cluster with v1.25 using Custom Launch Template
- Upgrade Cluster to 1.26 via Rancher UI (CP is updated at this step)
- Create new version of LT with respect to new EKS v1.26
- Upgrade Node group by selecting new LT version on Rancher UI

![image](https://github.com/rancher/eks-operator/assets/73099870/eb569028-a390-4c50-b9e0-7f0720c34589)

**Comment by salasberryfin** [comment]
`eks-operator:v1.2.2-rc3` has been released and should fix this error.

**Comment by cpinjani** [comment]
Validated as fixed on build - :white_check_mark: 
```
2.7-head - 95f0b50
eks-operator:v1.2.2-rc3
```

**Steps:**
- Provision EKS cluster with v1.25 using Custom Launch Template with AMI
- Upgrade Cluster to 1.26 via Rancher UI (CP is updated at this step)
- Create new version of LT with respect to new EKS v1.26 AMI
- Upgrade Node group by selecting new LT version on Rancher UI, it completes successfully

Provisioning Rancher with TF using Custom Launch template is tested here: https://github.com/rancher/eks-operator/issues/90#issuecomment-1633681623
